### PR TITLE
Add success message to the subscribe form

### PR DESCRIPTION
**Pull request by homer0**
- Updates the store in order to track the success and possible error of the email subscription form.
- Refactors the `AddEmailForm` in order to show a success message and a possible response error.
- Since the _"teaser text"_ needs to disappear when the user is on mobile and the subscription was successful... it was moved to another _(connected)_ component, that will add a class to hide it on mobile when the email is saved.
- I added extra padding of the content area when on mobile, following the XD design.

## WIP notes (OUTDATED)

When showing the success message the paragraph that goes above the form is hidden, so I first moved the paragraph to the component and wrapped both it and the form on a new container, that way we can simply toggle containers when we show the success message.

Now; since I didn't have the `xd` "file" for the screen, I used the screenshot @joelalejandro shared on Telegram and assumed the font size was the same as the current text. We should confirm if those styles are correct.

Finally, @asermax, I pushed this as a WIP because I didn't want to touch the store :P. I had a few questions and since you made the integration, you probably had an idea of how to do it than I'm not sure I'm seeing. You defined that "part of the store" just as a boolean, but you knew we were going to have a _"success state"_, so I had a two theories:

1. The basic one: You were going to refactor the store.
2. You were going to check if `isAdding` changed from `true` to `false` and `errors` was `null` in order to show the message (Not sure how to this now).

Whatever you decide, let me know and I'll update the PR.

### To-Do

- [ ] Style validation by @joelalejandro 
- [x] _"Success state"_ validation by @asermax

### CODE REVIEW

**Comment by asermax** [comment]
I didn't really think it through, so let's go for 1. It sounds easier to hold a a status key to track success/error states and a another key to keep possible backend errors, then the component can just react to prop changes.

**Comment by joelalejandro** [comment]
@homer0 Sorry for the delay, this is the XD for the full landing page implementation:
https://xd.adobe.com/spec/90d8c9e1-5a73-48c1-7aa7-8c7bc48338cc-e6e9/

**Comment by joelalejandro** [comment]
🛑 Checking design...

**Comment by joelalejandro** [comment]
Success state looks :100:  :ok_hand:  Some comments though (no blockers).

**Desktop & Mobile:**

- There should be no wording in English anywhere. "Network Error" should read "Algo salió mal. Intentá de nuevo más tarde". Any error code we handle should be described in a human, user-friendly way.

**Mobile:**

- The `.index--module--middle-section` shouldn't be full width, that way there's no need to use padding for the brackets. This breaks a bit both legibility and layout on screens smaller than <375px.

**Pull request merged**
