### PR TITLE
Video and photos

### PR DESCRIPTION
**Pull request by asermax**
## What does this PR do?
Modifies the main page to show the webconf summary video and add the photos section. 

### Notes:
- Upgraded dependencies minor versions (including gatsby) to be able to use some features and to fix the security warning issue on the repo.
- Implemented a Gatsby plugin to bring photos from the facebook album where we published our selection. Let me know if we want to use a different source for the photos.
- Hardcoded some resolution values on the code since we need pixels numbers and the constants use `rem` let me know if I should change it or it's okay as it is.
- Had to implement two separate photo picker components depending on the browser resolution since their structure and behaviour are pretty different.
- Did my best to add some lazy loading/preloading to avoid overfetching but still trying to preserve a good UX.
- Just noticed a weird "jump" when switching between pages on the photo's picker for desktop, not sure why it's happening, need to investigate.
- Something to take into account: browsers have some weird policies on autoplaying videos nowaday, that may affect the home's fullscreen video. I'm not sure if we can ask the user for autoplay permission or adding some way for the user to start the video themselves. We may have to research that.

## How should it be tested manually?
Go to the deploy and check the home and photos section's design against the designs at https://xd.adobe.com/spec/bddd016f-156f-466b-5d06-8c8128fc6216-cbec/.
Also make sure to check that the behaviour of the photo picker and it's lazy loading/prefetching works as expected.

### CODE REVIEW

**Comment by homer0** [comment]
- The code looks good overall, there a few **really minor issues**, but we can live with them... the only thing that really worries me is the change of the working directory you did on the `build` script.
- I couldn't found the bug you described on the PR, the weird "jump".
- Not sure if this is related to the privacy policies regarding autoplay, but when I landed on the page, the video started playing; then I went to the photos and clicked on the close icon... it took me back to the home, but the video didn't start playing, I see the play button but I can't click it.

**Comment by asermax** [comment]
- The `cwd` is because the gatsby plugin has it's own `package.json` and I coudn't find any other wire to fire it's dependencies installation. The only other option I can think of is not having it as a plugin and just putting it within the `gatsby-nodes` of the project itself (I asume it works in the same way).
- It seems it had something to with the lazy load component I used, I think I fixed it.
- I have no idea of why that happens, it did happen to me as well. Sometimes it autoplays, sometimes it doesn't. We can try making the play button work, not sure why it isn't working right now.

Feel free to take a shot at any of these issues, I may not be able to this week since I will be travelling.

**Comment by joelalejandro** [comment]
@asermax Take a look at this implementation for the video component:

https://codepen.io/joelalejandro/full/YbayMP

This deals with autoplay issues and video scaling.

**Comment by homer0** [comment]
@asermax @joelalejandro things got haaaacky xD

First, for some reason, the example of the pen wasn't working; I went to the API docs and then I realized that it was using an old version, switching it got it to work... but no idea why on the pen worked too.

Ok, so I did a small service a component consumes in order to show the video anda everything was great, but when I went for the mobile view...

To make the same component work for both view I had to:

1. Make the resize listener (for the proportions) for full screen work in both cases.
2. Have a way to modify the instance based on the size of the player.

For both cases, I needed to know the size from JS, but if I was going to do that, I wanted to do it the simplest way possible: I built a small component that uses render props to show a component on desktop and another on mobile xD.

I used all the hooks I knew of, it felt [so.... ](https://i1.wp.com/culturageek.com.ar/wp-content/uploads/2016/05/hacker.jpg)

Let me know if it works.

**Comment by joelalejandro** [comment]
IT WORKS! :D

**Pull request merged**
